
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-06T11:02:07-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e68a2445e966c215b1ec92c857487a3c8c83811e",
 "version": "2.23.3b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
