
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-06T00:00:52-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "b9c6d3559d8f43f7a506aabcc16032aed9755f38",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
