
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-06T12:58:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef6c38669050196e0bd27491ea1b46629cfb4557",
 "version": "0.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
