from StenLib.StenUtils import Utils as Utils
from pathlib import Path
from typing import Optional, Union

class DataBase(Utils):
    @classmethod
    def load(cls, file_name: Optional[Union[str, None]] = ...) -> Union[list[Path], Path]: ...
    @classmethod
    def write(cls, data: dict, file_name: str) -> None: ...
    @classmethod
    def read(cls, file_name: Optional[Union[str, None]] = ...) -> dict: ...
    @classmethod
    def create(cls, file_name: str) -> None: ...
    @classmethod
    def delete(cls, file_name: str) -> None: ...
