
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-08T14:40:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a0df4dd779e3be53bc1432200745c023f9ca5659",
 "version": "1.0.0.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
