HAS_CUDA = 0
CXX_FLAGS = '/DWIN32 /D_WINDOWS /EHsc /arch:AVX'
CMAKE_CXX_STANDARD_REQUIRED = ''
CMAKE_CXX_EXTENSIONS = ''
CMAKE_CXX_STANDARD = 11

# Was compiled with the following versions.
CYTHON_VERSION = '3.0.5'
SKLEARN_VERSION = '1.3.2'
NUMPY_VERSION = '1.26.1'
SCIPY_VERSION = '1.11.3'
