'''
Constants that serve as dictionary keys for the gameclock.
'''
MINUTES = 'minutes'
HOURS = 'hours'
DAY = 'day'
MONTH = 'month'
YEAR = 'year'
DAYS_IN_MONTH = 'days_in_month'
DAY_OF_MONTH = 'day_of_month'
DAYS_IN_WEEK = 'days_in_week'
DAY_OF_WEEK = 'day_of_week'
LEAP_YEAR = 'leap_year'
LEAP_YEAR_FREQUENCY = 'leap_year_frequency'
LEAP_MONTH = 'leap_month'
MINUTES_IN_HOUR = 'minutes_in_hour'
HOURS_IN_DAY = 'hours_in_day'

NEXT = 'next'
PREVIOUS = 'previous'
LINEAR = 'linear'
CIRCULAR = 'circular'