
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-06T13:41:14-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "371ec5f965ceecb7dbc306a1de135a3cf704a8e0",
 "version": "2023.11.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
