
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-02T16:44:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "93c19a4177f33ef6d73f66375d5c203fb6d511f0",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
