"""
This file is generated by sqldao-generator;
you can modify connection properties yourself.
"""
import os

from sqlalchemy import create_engine

from sqldaogenerator.common.Database import Database


class Datasource(Database):

    def __init__(self):
        username = os.getenv('username')
        password = os.getenv('password')
        host = os.getenv('host')
        port = os.getenv('port')
        dbname = os.getenv('dbname')
        connection_string = f"mysql+mysqlconnector://{username}:{password}@{host}:{port}/{dbname}"
        self.engine = create_engine(connection_string,
                                    echo=os.getenv('echo') == 'True',
                                    pool_recycle=270)
        super().__init__(os.getenv('transaction_name'))


datasource = Datasource()
