import numpy as np

def moisture(temperature: float, relative_humidity: float, pressure: float) -> np.ndarray: ...
def wet_bulb_temperature(temperature: float, relative_humidity: float) -> float: ...
