# Generated by Django 4.1.10 on 2023-11-05 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 5, 18, 44, 29, 444242, tzinfo=datetime.timezone.utc), verbose_name='Created'),
            preserve_default=False,
        ),
    ]
