
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-08T00:41:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c97751afacb1a50124398c2a56438d00bd1bbd1e",
 "version": "2.23.3rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
