# -*- coding: utf-8 -*-
"""
    pip_services3_commons.validate.ValidationResultType
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    Validation result type enumeration
    
    :copyright: Conceptual Vision Consulting LLC 2018-2019, see AUTHORS for more details.
    :license: MIT, see LICENSE for more details.
"""
from enum import Enum


class ValidationResultType(Enum):
    """
    Types of validation results generated by validation schemas.
    """
    # General information (not an error).
    Information = 0
    # Warning about something suspecious. In strict mode is treated as error
    Warning = 1
    # Validation error.
    Error = 2
