
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-29T10:24:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "57892e8d245298f96d91c91d1aebf0c53d850cc1",
 "version": "0.10.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
