#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2305-13-g790f4784"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2305
#define NETGEN_VERSION_TWEAK 13
#define NETGEN_VERSION_HASH "g790f4784"
#endif // NETGEN_VERSION_HPP_INCLUDED
