WM_MOUSEMOVE = "WM_MOUSEMOVE",
WM_LBUTTONDOWN = "WM_LBUTTONDOWN",
WM_LBUTTONUP = "WM_LBUTTONUP",
WM_LBUTTONDBLCLK = "WM_LBUTTONDBLCLK",
WM_RBUTTONDOWN = "WM_RBUTTONDOWN",
WM_RBUTTONUP = "WM_RBUTTONUP",
WM_RBUTTONDBLCLK = "WM_RBUTTONDBLCLK",
WM_MBUTTONDOWN = "WM_MBUTTONDOWN",
WM_MBUTTONUP = "WM_MBUTTONUP",
WM_MBUTTONDBLCLK = "WM_MBUTTONDBLCLK"

ADD = "add"
APPLICATION = "application"

MESSAGE = "%message"
X = "%x"
Y = "%y"
