# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist
from bgrafana_api.models.query_to_migrate import QueryToMigrate

class MigrateQueriesToQueryHistoryCommand(BaseModel):
    """
    MigrateQueriesToQueryHistoryCommand is the command used for migration of old queries into query history  # noqa: E501
    """
    queries: Optional[conlist(QueryToMigrate)] = Field(None, description="Array of queries to store in query history.")
    __properties = ["queries"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MigrateQueriesToQueryHistoryCommand:
        """Create an instance of MigrateQueriesToQueryHistoryCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in queries (list)
        _items = []
        if self.queries:
            for _item in self.queries:
                if _item:
                    _items.append(_item.to_dict())
            _dict['queries'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MigrateQueriesToQueryHistoryCommand:
        """Create an instance of MigrateQueriesToQueryHistoryCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MigrateQueriesToQueryHistoryCommand.parse_obj(obj)

        _obj = MigrateQueriesToQueryHistoryCommand.parse_obj({
            "queries": [QueryToMigrate.from_dict(_item) for _item in obj.get("queries")] if obj.get("queries") is not None else None
        })
        return _obj


