# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Dict, Optional
from pydantic import BaseModel, Field, StrictStr

class PostableAlert(BaseModel):
    """
    PostableAlert postable alert  # noqa: E501
    """
    annotations: Optional[Dict[str, StrictStr]] = Field(None, description="LabelSet label set")
    ends_at: Optional[datetime] = Field(None, alias="endsAt", description="ends at Format: date-time")
    generator_url: Optional[StrictStr] = Field(None, alias="generatorURL", description="generator URL Format: uri")
    labels: Dict[str, StrictStr] = Field(..., description="LabelSet label set")
    starts_at: Optional[datetime] = Field(None, alias="startsAt", description="starts at Format: date-time")
    __properties = ["annotations", "endsAt", "generatorURL", "labels", "startsAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PostableAlert:
        """Create an instance of PostableAlert from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PostableAlert:
        """Create an instance of PostableAlert from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PostableAlert.parse_obj(obj)

        _obj = PostableAlert.parse_obj({
            "annotations": obj.get("annotations"),
            "ends_at": obj.get("endsAt"),
            "generator_url": obj.get("generatorURL"),
            "labels": obj.get("labels"),
            "starts_at": obj.get("startsAt")
        })
        return _obj


