# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr
from bgrafana_api.models.slack_confirmation_field import SlackConfirmationField

class SlackAction(BaseModel):
    """
    See https://api.slack.com/docs/message-attachments#action_fields and https://api.slack.com/docs/message-buttons for more information.  # noqa: E501
    """
    confirm: Optional[SlackConfirmationField] = None
    name: Optional[StrictStr] = None
    style: Optional[StrictStr] = None
    text: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    value: Optional[StrictStr] = None
    __properties = ["confirm", "name", "style", "text", "type", "url", "value"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SlackAction:
        """Create an instance of SlackAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of confirm
        if self.confirm:
            _dict['confirm'] = self.confirm.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SlackAction:
        """Create an instance of SlackAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SlackAction.parse_obj(obj)

        _obj = SlackAction.parse_obj({
            "confirm": SlackConfirmationField.from_dict(obj.get("confirm")) if obj.get("confirm") is not None else None,
            "name": obj.get("name"),
            "style": obj.get("style"),
            "text": obj.get("text"),
            "type": obj.get("type"),
            "url": obj.get("url"),
            "value": obj.get("value")
        })
        return _obj


