
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-07T20:17:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "59fe727b3bad13a014d5825382766ebd876638b6",
 "version": "2023.11.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
