
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-06T14:57:21+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dea848541e389a7ec26d0e578c3f28aa5502f599",
 "version": "2.9.17.post0.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
