
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-06T11:15:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebc7d3bbe92cc2e6a5730fcd1432e728095fef61",
 "version": "0.4.0.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
