# Generated by Django 4.2.7 on 2023-11-05 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artd_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                help_text="Order",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="artd_order.order",
                verbose_name="Order",
            ),
        ),
    ]
