# Generated by Django 3.2.21 on 2023-11-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token_exchange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenexchangeconfiguration",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="The label of this token exchange configuration",
                max_length=250,
                verbose_name="label",
            ),
        ),
    ]
