
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-07T11:37:29-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "94f92dea07e2fd3939c15468fe6d0a5ff6353ddf",
 "version": "1.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
