
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-08T13:48:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "47f936029fa77c2dd495571a77cd26c7f81dbd0d",
 "version": "0.1.7.post0.dev199"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
