
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-04T11:07:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "62fa0db1591d90eddfa52c18539c76527e3aa5fd",
 "version": "1.2.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
