# Generated by Django 4.2.6 on 2023-11-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subsystems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsystem',
            name='security_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='security_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
